##### 1. Import numpy as np and see the version

In [ ]:
import numpy as np
print(np.__version__)

##### 2. How to create a 1D array?

In [ ]:
arr_1D = np.arange(10)
print(arr_1D)

3. How to create a boolean array?

In [ ]:
arr_bool = np.full((3,3),True, dtype=bool)
arr_bool = np.full((9),True, dtype=bool).reshape(3,3)
print(arr_bool)

arr_ones = np.ones((3,3),dtype=bool)
print(arr_ones)

arr_zero = np.zeros((3,3),dtype=bool)
print(arr_zero)

4. How to extract items that satisfy a given condition from 1D array?

In [ ]:
arr = np.arange(10)
arr_odd = arr[arr % 2 == 1]
print(arr_odd)

5. How to replace items that satisfy a condition with another value in numpy array?

In [ ]:
arr = np.arange(10)
arr[(arr % 2 == 1)] = -1
print(arr)

6. How to replace items that satisfy a condition without affecting the original array?

In [ ]:
arr = np.arange(10)
out = arr.copy()
out[(out % 2 == 1)] = -1

print("Original : ",arr)
print("Modify : ",out)

7. How to reshape an array?

In [ ]:
#-1 automatically decides the number of columns / rows
arr = np.arange(12).reshape(-1,3) 
print(arr)
print("Shape :",arr.shape)
print("Size :",arr.size)
print("Type :",arr.dtype)
print("ItemSize :",arr.itemsize)

8. How to stack two arrays vertically or horizontally?

In [ ]:
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)

stack = np.stack((arr2,arr1),axis=1)
print(stack,"\n")

vstack = np.vstack((arr2,arr1))
hstack = np.hstack((arr1,arr2))
print("Add vertically :\n",vstack)
print()
print("Add horizontally :\n",hstack )

10. How to generate custom sequences in numpy without hardcoding?

In [ ]:
a = np.array([1,2,3])
# np.r_[np.repeat(a,3), np.tile(a,3)]
print(np.repeat(a,3)) 
print(np.repeat(a,[2,2,2]))

print(np.tile(a,3))
print(np.tile(a,(3,2))) # 3 array 2 times every arry


11. How to get the common items between two python numpy arrays?

In [65]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

12. How to remove from one array those items that exist in another?

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.setdiff1d(a,b))

[1 2 3 2 3 4 3 4 5 6]
[1 3 5 6]


13. How to get the positions where elements of two arrays match?

In [77]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.where(a == b)

print(c)

(array([1, 3, 5, 7]),)


14. How to extract all numbers between a given range from a numpy array?

In [85]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# b = np.where((a >= 5) & (a <= 10))
# print(a[b])

a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])