In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 8)

print(newarr)

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

for x in np.nditer(matrix):
  print(x)

In [22]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])

b = np.array([[9,10,11,12],
              [13,14,15,16]])

c = np.concatenate((a,b),axis=1)
print(c)
print()
d = np.concatenate((a,b),axis=0)
print(d)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.hstack((a,b))
d = np.vstack((a,b))
e = np.concatenate((a,b))

print(c)
print(d)
print(e)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
